import type { SkyPhase } from "../lib/sunPhase";

export const poemsByPhase: Record<SkyPhase, string[]> = {
  night: [
    "Dem tham, nhip tho cham lai de nghe minh o day.",
    "Troi toi khong thuc giuc, ban cung khong can voi.",
    "Giua khoang lang, mot y nghi nhe nhu sao roi.",
    "Dem nay mem nhu vai lanh, cu de long nghi tren do.",
    "Thanh pho da cham dan, tim ban cung co the cham theo.",
    "Mot chut yen tu ben trong quy hon nhieu cai hen.",
    "Den khong ep ai nhanh, dem cung vay.",
    "Troi cao va sau, minh nho hit mot hoi that dai.",
    "Khi sao im, long nguoi de dang nghe duoc minh hon.",
  ],
  dawn: [
    "Binh minh dung nhat vo vang, no den nhu mot loi chao.",
    "Troi sap sang, long nguoi cung nen mo cua so.",
    "Anh hong dau ngay dang go cua, nhe thoi.",
    "Sac sang dang lo ra tu mep troi, tu tu nhu mot nu cuoi.",
    "Ngay moi khong doi ban hoan hao, chi can ban bat dau.",
    "Tieng sang dau tien thuong nho, nhung du suc danh thuc hy vong.",
    "Moi som mai la mot to giay trang, cu viet mot dong that hiền.",
    "Binh minh la loi nhac rang bat dau lai luon co that.",
    "Anh hong tan ra, du de long minh am hon mot chut.",
  ],
  morning: [
    "Sang nay nhe nhu hoi tho dau ngay.",
    "Nang moi len, ban da uong mot ngum nuoc chua?",
    "May troi cham, de minh di cham theo.",
    "Buoi sang mo nhu mot ban nhac khong loi, de long tu dieu chinh.",
    "Anh nang trong, nho ban noi nhe voi chinh minh.",
    "Ngay con dai, minh co the chon cach di nhe nhang.",
    "Bau troi xanh nhac rang su on dinh bat dau tu nhung viec nho.",
    "Nhap mot ngum nuoc, duoi vai, va di tiep that em.",
    "Moi tia nang la mot loi dong vien khong tieng.",
  ],
  noon: [
    "Mat troi dung bong, tim minh cung nghi mot chut.",
    "Giua trua, khoang lang la mon qua quy.",
    "Anh sang day, nhung ngay van co the mem.",
    "Giua ngay, cho phep minh dung lai khong phai la tre nan.",
    "Nang cao, tam tri nen hop lai mot chut de tho.",
    "Ngay nang la luc minh nho uong nuoc va thu gian ham.",
    "Ban co the cham hon, va van den noi can den.",
    "Giua trua, mot khoanh khac yen da du de lam moi.",
    "Nang sang khong bat minh hoang hot.",
  ],
  afternoon: [
    "Chieu nghieng nhe, cong viec cung nen nhe lai.",
    "Nang xech vai, minh thuong minh them mot chut.",
    "May troi qua, nhac ban tam dung va hit sau.",
    "Buoi chieu keo dai nhu loi nhac nen, de minh don dep y nghi.",
    "Mat troi di cham ve tay, minh cung giam nhip mot chut.",
    "Neu da met, hay de gio troi di ho mot phan cho ban.",
    "Chieu la luc dep de ket thuc viec dang do bang mot buoc nho.",
    "Nang chieu am, noi minh do dang noi.",
    "Khong can xong het moi duoc nghi, nghi de di tiep cung tot.",
  ],
  sunset: [
    "Mat troi dang nghieng mot goc, ban da uong nuoc chua?",
    "Hoang hon do mot vet son len bau troi.",
    "Ngay sap khuan lai, long minh cung the.",
    "Mau troi dang doi, minh cung co the doi cach nho ve ngay nay.",
    "Hoang hon la cai om nhe giua on ao va im lang.",
    "Anh vang cam rot xuong, gom lai nhung dieu du cua mot ngay.",
    "Ngay dai den dau roi cung biet cach nhe dan.",
    "Khi troi do, dung quen khen minh da co gang.",
    "Mot chut dung lai luc hoang hon thuong giup dem den em hon.",
  ],
  dusk: [
    "Chap choang giua sang va toi, moi thu deu co the tu ton tai.",
    "Mot khoanh khac tim than, du cho ngay dai den dau.",
    "Den len cham cham, minh cung cham cham thoi.",
    "Chap choang la nhip cau dep giua viec lam va viec nghi.",
    "Khi den vua bat, co nhung dieu nen de lai cho ngay mai.",
    "Tim toi khong vo vang, no toi tu tu va rat nhe.",
    "Mot ngay da du, bay gio den luot su lang y.",
    "Doi mat quen voi bong toi, long cung quen voi su thu thai.",
    "Khoang giao mua cua anh sang luon dang de duoc triu menh.",
  ],
};


