import type { SkyPhase } from "../lib/sunPhase";

export const poemsByPhase: Record<SkyPhase, string[]> = {
  night: [
    "Đêm thẳm, nhịp thở chậm lại để nghe mình ở đây.",
    "Trời tối không thúc giục, bạn cũng không cần vội.",
    "Giữa khoảng lặng, một ý nghĩ nhẹ như sao rơi.",
    "Đêm nay mềm như vải lạnh, cứ để lòng nghỉ trên đó.",
    "Thành phố đã chậm dần, tim bạn cũng có thể chậm theo.",
    "Một chút yên từ bên trong quý hơn nhiều cái hẹn.",
    "Đèn không ép ai nhanh, đêm cũng vậy.",
    "Trời cao và sâu, mình nhớ hít một hơi thật dài.",
    "Khi sao im, lòng người dễ dàng nghe được mình hơn.",
  ],
  dawn: [
    "Bình minh đúng nhất vô vàn, nó đến như một lời chào.",
    "Trời sắp sáng, lòng người cũng nên mở cửa sổ.",
    "Ánh hồng đầu ngày đang gõ cửa, nhẹ thôi.",
    "Sắc sáng đang lộ ra từ mép trời, từ từ như một nụ cười.",
    "Ngày mới không đòi bạn hoàn hảo, chỉ cần bạn bắt đầu.",
    "Tiếng sáng đầu tiên thường nhỏ, nhưng đủ sức đánh thức hy vọng.",
    "Mỗi sớm mai là một tờ giấy trắng, cứ viết một dòng thật hiền.",
    "Bình minh là lời nhắc rằng bắt đầu lại luôn có thật.",
    "Ánh hồng tản ra, đủ để lòng mình ấm hơn một chút.",
  ],
  morning: [
    "Sáng nay nhẹ như hơi thở đầu ngày.",
    "Nắng mới lên, bạn đã uống một ngụm nước chưa?",
    "Mây trôi chậm, để mình đi chậm theo.",
    "Buổi sáng mở như một bản nhạc không lời, để lòng tự điều chỉnh.",
    "Ánh nắng trong, nhờ bạn nói nhẹ với chính mình.",
    "Ngày còn dài, mình có thể chọn cách đi nhẹ nhàng.",
    "Bầu trời xanh nhắc rằng sự ổn định bắt đầu từ những việc nhỏ.",
    "Nhấp một ngụm nước, duỗi vai, và đi tiếp thật êm.",
    "Mỗi tia nắng là một lời động viên không tiếng.",
  ],
  noon: [
    "Mặt trời đứng bóng, tim mình cũng nghỉ một chút.",
    "Giữa trưa, khoảng lặng là món quà quý.",
    "Ánh sáng đầy, nhưng ngày vẫn có thể mềm.",
    "Giữa ngày, cho phép mình dừng lại không phải là trễ nải.",
    "Nắng cao, tâm trí nên khép lại một chút để thở.",
    "Ngày nắng là lúc mình nhớ uống nước và thư giãn hàm.",
    "Bạn có thể chậm hơn, và vẫn đến nơi cần đến.",
    "Giữa trưa, một khoảnh khắc yên đã đủ để làm mới.",
    "Nắng sáng không bắt mình hoảng hốt.",
  ],
  afternoon: [
    "Chiều nghiêng nhẹ, công việc cũng nên nhẹ lại.",
    "Nắng xếch vai, mình thương mình thêm một chút.",
    "Mây trôi qua, nhắc bạn tạm dừng và hít sâu.",
    "Buổi chiều kéo dài như lời nhạc nền, để mình dọn dẹp ý nghĩ.",
    "Mặt trời đi chậm về tây, mình cũng giảm nhịp một chút.",
    "Nếu đã mệt, hãy để gió trời đi hộ một phần cho bạn.",
    "Chiều là lúc đẹp để kết thúc việc dang dở bằng một bước nhỏ.",
    "Nắng chiều ấm, nơi mình đỡ gồng hơn.",
    "Không cần xong hết mới được nghỉ, nghỉ để đi tiếp cũng tốt.",
  ],
  sunset: [
    "Mặt trời đang nghiêng một góc, bạn đã uống nước chưa?",
    "Hoàng hôn đổ một vệt son lên bầu trời.",
    "Ngày sắp khuất lại, lòng mình cũng thế.",
    "Màu trời đang đổi, mình cũng có thể đổi cách nhớ về ngày này.",
    "Hoàng hôn là cái ôm nhẹ giữa ồn ào và im lặng.",
    "Ánh vàng cam rót xuống, gom lại những điều đủ của một ngày.",
    "Ngày dài đến đâu rồi cũng biết cách nhẹ dần.",
    "Khi trời đỏ, đừng quên khen mình đã cố gắng.",
    "Một chút dừng lại lúc hoàng hôn thường giúp đêm đến êm hơn.",
  ],
  dusk: [
    "Chập choạng giữa sáng và tối, mọi thứ đều có thể tự tồn tại.",
    "Một khoảnh khắc tĩnh thân, dù cho ngày dài đến đâu.",
    "Đèn lên chầm chậm, mình cũng chầm chậm thôi.",
    "Chập choạng là nhịp cầu đẹp giữa việc làm và việc nghỉ.",
    "Khi đèn vừa bật, có những điều nên để lại cho ngày mai.",
    "Tím tối không vội vàng, nó tới từ từ và rất nhẹ.",
    "Một ngày đã đủ, bây giờ đến lượt sự lắng yên.",
    "Đôi mắt quen với bóng tối, lòng cũng quen với sự thư thái.",
    "Khoảng giao mùa của ánh sáng luôn đáng để được trìu mến.",
  ],
};

